# Generated by Django 6.0 on 2026-01-05 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=200)),
                ('date_of_event', models.DateTimeField(blank=True, null=True)),
                ('venue_of_event', models.TextField()),
                ('photo_of_event', models.ImageField(blank=True, null=True, upload_to='event_image/')),
                ('description_of_event', models.TextField(blank=True, null=True)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('price_of_tickets', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_of_event', models.CharField(blank=True, choices=[('parties', 'Parties'), ('sports', 'Sports'), ('technology', 'Technology'), ('conference', 'Conference')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
