# Generated by Django 6.0 on 2026-01-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='photo_of_event',
        ),
    ]
