# Generated by Django 6.0 on 2026-01-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_events_photo_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo_of_event',
            field=models.ImageField(blank=True, null=True, upload_to='event_image/'),
        ),
    ]
